version: "3.9"

services:
    java_app:
        container_name: java_app
        image: maty-java-app:1.0.0
        build: .
        ports:
            - "8080:8080"
        environment:
            - DB_URL=jdbc:postgresql://java_db:5432/postgres
            - DB_USER_NAME=maty
            - DB_PASSWORD=123
        restart: always
        depends_on:
            - java_db
    java_db:
        container_name: java_db
        image: postgres:15
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres