version: "3"

services:
    app_vet:
        build: deploy_app
        ports:
            - "8080:8080"
        environment:
            DB_URL: jdbc:postgresql://deploy_app:5432/postgres?createDatabaseIfNotExist=true&serverTimezone=UTC
            DB_USER_NAME: maty
            DB_PASSWORD: 123
        restart: always
        depends_on:
            deploy_app:
                condition: service_healthy
    deploy_app:
        image: postgres:15
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: maty
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: postgres
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U maty"]
            interval: 10s
            timeout: 5s
            retries: 5
