version: "3.9"

services:
    java_app:
        container_name: java_app
        image: maty-java-app:1.0.0
        build: deploy_app
        ports:
            - "8080:8080"
        environment:
            - DB_URL=jdbc:postgresql://java_db:5432/postgres?createDatabaseIfNotExist=true&serverTimezone=UTC
            - DB_USER_NAME=maty
            - DB_PASSWORD=123
        restart: always
        depends_on:
            java_db:
                condition: service_healthy
    java_db:
        image: postgres:15
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: maty
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: postgres
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U maty"]
            interval: 10s
            timeout: 5s
            retries: 5
